{"uuid": "42b7b530-2bd3-47f0-bca2-5b0da903489f", "children": ["5200c3a2-3dde-477e-bd3c-8a9458283b62", "3caf5543-ae96-4dd6-9dcb-2592a2ee7081", "62f39524-61ef-4c27-a8c4-41b46fe30888"], "befores": [{"name": "_xunit_setup_class_fixture_Test_login", "status": "broken", "statusDetails": {"message": "AttributeError: type object 'Test_login' has no attribute 'init_driver'\n", "trace": "  File \"E:\\python37\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"E:\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"E:\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 917, in call_fixture_func\n    fixture_result = next(generator)\n  File \"E:\\python37\\lib\\site-packages\\_pytest\\python.py\", line 829, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"E:\\python37\\lib\\site-packages\\_pytest\\python.py\", line 751, in _call_with_optional_argument\n    func(arg)\n  File \"F:\\xiejun-data\\pyteststudy\\pytest_test_pom\\test_suit\\test_login.py\", line 25, in setup_class\n    cls.driver = cls.init_driver()\n"}, "start": 1640855495598, "stop": 1640855495598}], "start": 1640855495598, "stop": 1640855495695}